### ISSUE TITLE
attribute setter method should typecast value to appropriate cassandra data type

### ISSUE THREAD

**Issue by gabrielmansour** [thomasrogers03/cassandra_model#2]
e.g.

    record.double_field = "7.89"
    record.double_field # => 7.89

**Comment by thomasrogers03** [comment]
Perhaps I could add it as an option (maybe enabled by default). Primarily, I'd like the overhead to be as light as possible (possibly to the point of overkill, not sure) so that the applications using it can focus on saturating the network, rather than processing time. 

If I see a few more use cases I might do this, as there still a number of directions I'm not sure about yet going with the model.
